export const siteConfig = {
  name: "Yanuar Bima",
  displayName: "Yanuar Bima",
  shortName: "Bima",
  title: "Yanuar Bima | Full Stack Developer Portfolio",
  description:
    "Yanuar Bima (Bima) is a Full Stack Developer from Indonesia specializing in React, Next.js, Laravel, Golang, and modern web applications. Available for freelance and full-time opportunities.",
  keywords: [
    "Yanuar Bima",
    "Bima developer",
    "Full Stack Developer Indonesia",
    "React developer",
    "Next.js developer",
    "Laravel developer",
    "Golang developer",
    "freelance web developer Indonesia",
    "portfolio web developer",
    "hire full stack developer",
  ],
  url:
    process.env.NEXT_PUBLIC_SITE_URL ?? "https://bima.cleveragent.site",
  locale: "en_ID",
  language: "en",
  email: "bima.aji1380@gmail.com",
  location: "Indonesia",
  countryCode: "ID",
  role: "Full Stack Developer",
  subtitle: "Available For Freelance",
  heroTitle:
    "Hello, I'm Yanuar Bima, Full Stack Developer and modern web specialist based in Indonesia.",
  heroHighlight: "building scalable digital products",
  yearsExperience: "5+",
  clientsCount: "20+",
  cvPath: "/YanuarBimaCV.pdf",
  ogImage: "/assets/imgs/header/profile.jpeg",
  ogImageWidth: 500,
  ogImageHeight: 500,
  social: {
    linkedin: "https://www.linkedin.com/in/yanuar-bima",
    github: "https://github.com/Bima1301",
    gitlab: "https://gitlab.com/bima.aji1380",
    instagram: "https://instagram.com/yanuar.bimantoro",
  },
} as const;
